/**
 * build.js
 *
 * Stamps git short hash + UTC timestamp into src/build-info.js.
 * Run as the Cloudflare Pages build command: node build.js
 */

import { execSync } from "child_process";
import { writeFileSync } from "fs";

const hash = execSync("git rev-parse --short HEAD").toString().trim();
const date = new Date().toISOString().replace("T", " ").slice(0, 16) + " UTC";

const content = `// Auto-generated by build.js — do not edit
window.BUILD_INFO = { hash: "${hash}", date: "${date}" };
`;

writeFileSync("src/build-info.js", content);
console.log(`[build] Stamped build-info: ${hash} @ ${date}`);
